apiVersion: v1
kind: Secret
metadata:
  name: casino-secrets
type: Opaque
data:
  # Base64 encoded values. Replace with real ones before applying.
  DB_HOST: cG9zdGdyZXM= # postgres
  DB_PORT: NTQzMg== # 5432
  DB_USER: Y2FzaW5v # casino
  DB_PASSWORD: cGFzc3dvcmQ= # password
  DB_NAME: Y2FzaW5vX2Ri # casino_db
  JWT_SECRET: c2VjcmV0LWtleS1tdXktc2VndXJh # secret-key-muy-segura
